import { jsPDF } from 'jspdf';

const DARK  = [45, 41, 38];
const GREEN = [87, 161, 119];
const GRAY  = [92, 86, 80];
const LGRAY = [231, 227, 218];
const OFF   = [247, 245, 242];
const WHITE = [255, 255, 255];

const money = n => (n < 0 ? '-$' : '$') + Math.abs(Math.round(n)).toLocaleString('en-US');

function buildInvoicePDF(company, month, projects) {
  const doc   = new jsPDF({ unit: 'pt', format: 'letter' }); // 612 × 792
  const W     = 612;
  const total = projects.reduce((s, p) => s + p.revenue, 0);
  const date  = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const invNo = `INV-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 9000) + 1000)}`;

  // ── Dark header bar ─────────────────────────────────────────────
  doc.setFillColor(...DARK);
  doc.rect(0, 0, W, 90, 'F');

  // P badge
  doc.setFillColor(...GREEN);
  doc.roundedRect(40, 22, 46, 46, 6, 6, 'F');
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('P', 63, 53, { align: 'center' });

  // Firm name + sub
  doc.setFontSize(13);
  doc.text('Pioneer Management Consulting', 98, 42);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(176, 170, 162);
  doc.text('Claude Close  ·  EPiC 2026', 98, 57);

  // INVOICE title (right)
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.text('INVOICE', W - 40, 47, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(176, 170, 162);
  doc.text(invNo, W - 40, 63, { align: 'right' });

  // ── Bill To + Meta ───────────────────────────────────────────────
  let y = 116;
  const col2 = 320;

  // Bill To
  doc.setFontSize(7.5); doc.setFont('helvetica', 'bold'); doc.setTextColor(...GRAY);
  doc.text('BILL TO', 40, y);
  doc.setFontSize(13); doc.setFont('helvetica', 'bold'); doc.setTextColor(...DARK);
  doc.text(company, 40, y + 17);

  // Meta columns
  [
    ['INVOICE DATE', date],
    ['BILLING PERIOD', `${month} 2026`],
    ['PAYMENT TERMS', 'Net 30'],
  ].forEach(([label, val], i) => {
    const my = y + i * 29;
    doc.setFontSize(7.5); doc.setFont('helvetica', 'bold'); doc.setTextColor(...GRAY);
    doc.text(label, col2, my);
    doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(...DARK);
    doc.text(val, col2, my + 14);
  });

  // ── Divider ──────────────────────────────────────────────────────
  y = 206;
  doc.setDrawColor(...LGRAY); doc.setLineWidth(1);
  doc.line(40, y, W - 40, y);

  // ── Table header ─────────────────────────────────────────────────
  y += 14;
  doc.setFillColor(...DARK);
  doc.rect(40, y, W - 80, 26, 'F');
  doc.setTextColor(...WHITE); doc.setFont('helvetica', 'bold'); doc.setFontSize(8);
  doc.text('PROJECT / ENGAGEMENT', 54, y + 17);
  doc.text('AMOUNT', W - 54, y + 17, { align: 'right' });

  // ── Table rows ───────────────────────────────────────────────────
  y += 26;
  projects.forEach((p, i) => {
    if (i % 2 === 0) { doc.setFillColor(...OFF); doc.rect(40, y, W - 80, 26, 'F'); }
    doc.setTextColor(...DARK); doc.setFont('helvetica', 'normal'); doc.setFontSize(10);
    // Truncate long project names
    const name = p.project.length > 60 ? p.project.slice(0, 58) + '…' : p.project;
    doc.text(name, 54, y + 17);
    doc.text(money(p.revenue), W - 54, y + 17, { align: 'right' });
    y += 26;
  });

  // ── Total ────────────────────────────────────────────────────────
  doc.setDrawColor(...LGRAY); doc.line(40, y, W - 40, y);
  y += 10;
  doc.setFillColor(...GREEN);
  doc.roundedRect(W - 210, y, 170, 34, 4, 4, 'F');
  doc.setTextColor(...WHITE); doc.setFont('helvetica', 'bold'); doc.setFontSize(11);
  doc.text('TOTAL DUE', W - 200, y + 22);
  doc.text(money(total), W - 54, y + 22, { align: 'right' });

  // ── Footer ───────────────────────────────────────────────────────
  const fy = 748;
  doc.setDrawColor(...LGRAY); doc.line(40, fy, W - 40, fy);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...GRAY);
  doc.text('Thank you for your partnership with Pioneer Management Consulting.', W / 2, fy + 16, { align: 'center' });
  doc.text(`Generated by Claude Close  ·  ${date}`, W / 2, fy + 28, { align: 'center' });

  const filename = `Invoice-${company.replace(/[^a-z0-9]/gi, '-')}-${month}-2026.pdf`;
  return { doc, filename };
}

export function downloadInvoicePDF(company, month, projects) {
  const { doc, filename } = buildInvoicePDF(company, month, projects);
  doc.save(filename);
}

export function getInvoiceBlob(company, month, projects) {
  const { doc, filename } = buildInvoicePDF(company, month, projects);
  return { blob: doc.output('blob'), filename };
}
